[platformio]
src_dir = src
default_envs = cabinet

[env:cabinet]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
board_build.flash_size = 16MB
board_build.partitions = default.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINOJSON_ENABLE_ARDUINO_STRING=1
    -DARDUINOJSON_ENABLE_STD_STRING=1
    -DCONFIG_FATFS_LFN_HEAP=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -I../common
    -Isrc
lib_extra_dirs =
    ..
lib_ignore =
    root_node
    cabinet_node
lib_ldf_mode = deep+
lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.3
    bblanchon/ArduinoJson @ ^6.21.5
